# Docker Compose Configuration File
# Filename: docker-compose.yml
# Purpose: To define and run a multi-container todo Docker application

# Author: Donato Cappiello

# Email: dino.cappiello@gmail.com

version: "3"

services:
  # Postgres service.
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  # API service.
  dj:
    # Custom name for the created container.
    container_name: dj

    # Builds image from the Dockerfile in the 'todo_backend/deploy' directory.
    build: todo_backend/deploy

    # Starts a Django development server.
    command: python manage.py runserver 0.0.0.0:80

    # Mounts a volume, mapping the './django_api' path on the host to '/src_code' in the container.
    # Changes to the code on the host will affect the code in the container.
    volumes:
      - ./todo_backend/django_api:/src_code

    # Maps port 80 on the host to port 80 in the container
    ports:
      - "80:80"

    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS=dev

  ng:
      container_name: ng
      build: todo_frontend
      ports:
        - "8080:80"
  
