# Generated by Django 4.2.7 on 2023-11-30 15:27

from django.db import migrations

def create_dummy_tasks(apps, schema_editor):
    Task = apps.get_model('todoapi', 'Task')

    Task(title='Cosa Nostra Tiramisu Challenge', description='Convince the Godfather to Start a Bakery Empire', location='Oxford, GB', temperature='10', is_done='False').save()
    Task(title='Undercover Don Beni', description='Teach Mafia Bosses the Art of Salsa Dancing',  location='London, GB', temperature='15', is_done='False').save()
    Task(title='Sicilian Showdown', description='Mafia-themed Talent Competition',  location='Palermo, IT', temperature='30', is_done='True').save()


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_tasks),
    ]
